%... The MatMol Group (2016)
     function [Jac] = jacobian_x(t,N)
%...
%... Set global variables
     global a b K N0
%...
%... Jacobian of logistic equation Nt  = (a-b*N)*N
%...  
%...      J  = a-2*b*N
%...
     Jac = a-2*b*N;
