%... The MatMol Group (2016)
%...   Heat equation on a rectangle
%...
%... The equation in 2D is given by
%...
%...   Tt = k[Txx + Tyy] 
%...          
%... It is defined on the rectangle [0,1]X[0,2]
%...
%... with the conditions:
%...
%...   IC = T(x,y,0) = 0
%...
%...   BCs : Dirichlet : T = 0 along (0,0)-(1,0) and (0,0)-(0,2)
%...
%...                     T = TM along (1,0)-(1,2) and (0,2)-(1,2)
%...
%... The problem paramters are
%...   k = 10
%...
%...   TM = 100
%...
%... the following code computes a solution to the 2D heat equation
%...
    close all
    clear all
%...
%... start a stopwatch timer
    tic
%...
%... set global variables
    global k TM 
    global nx ny D2x D2y
%...
%... model parameters
    TM = 100;
    k = 10;
%...
%... spatial grid
    x = [0:0.01:1]; y = [0:0.02:2];
    nx = length(x); ny = length(y); nv = nx*ny;
%...
%... initial conditions
    T0(1:nv,1) = zeros(nv,1);
%...
%... finite difference (FD) approximation of the spatial derivatives
%...
    D2x = five_point_centered_D2(x);
    D2y = five_point_centered_D2(y);
%...  
%... call to ODE solver 
%...
    t = [0:.01/3:.01];
%...
    [tout,Tout] = ode45(@heat_equation_pde,t,T0);
%...  
%... impose BCs 
%...
    for k = 1:length(tout)
        Tout(k,1:nx) = 0;                  % BC along y = 0
        Tout(k,1:nx:nx*(ny-1)+1) = 0;      % BC along x = 0
        Tout(k,nx:nx:nx*ny) = TM;          % BC along x = 1
        Tout(k,nx*(ny-1)+1:nx*ny)= TM;     % BC along y = 2
    end
%...  
%... plot results 
%...
    for j = 1:length(tout)
     	figure
    	u(ny:-1:1,:) = reshape(Tout(j,1:nv),nx,[])';
    	surf(x,y(ny:-1:1),u,'EdgeColor','none');
    	axis([0 1 0 2 0 100])
        xlabel('x'); ylabel('y'); zlabel('T(x,y)')
    end
%...  
%... isotherms 
%...
    for j = 1:length(t)
      figure
      u(ny:-1:1,:) = reshape(Tout(j,1:nv),nx,[])';
      [C,h] = contour(x,y(ny:-1:1),u);
      set(h,'ShowText','on','TextStep',get(h,'LevelStep')*2)
      axis([-.1 1.1 -.1 2.1])
      xlabel('x'); ylabel('y')
    end
%...     
%... read the stopwatch timer
    toc