%... The MatMol Group (2016)
     function xtt = spring_mass_ode_2(t,x)
%...
%... Set global variables
     global m k
%...
%... Transfer dependent variables  
     z = x;
%...      
%... Temporal derivatives
%...
     ztt  = -(k/m)*z;
%...
%... Transfer temporal derivatives
     xtt = ztt;
