%...  The Matmol group (2016)
     function xt = ewwe_pde(t,x)     
%...
%... set global variables
     global a p mu c;
     global z0 zL z n D1;
%...
%... spatial derivatives
%...    
     xz = D1*x;
%...
%... temporal derivatives
%...
     xt = -a*(x.^p).*xz;