%... The MatMol Group (2016)
%...   Generalized Burgers equation
%...
%...   ut = -(u*u)x - (u*u)y + eps*[nu(u)*ux]x + eps*[nu(u)*uy]y
%...
%...   -1.5 < x < 1.5     -1.5 < y < 1.5
%...
%...   0 < t < 0.6
%...
%...   eps = 0.5
%...
%...   nu(u) = 0 if |u| <= 0.5
%...   
%...           1 if |u| > 0.5
%...
%...   ICs :
%...
%...       u(x,y,0) = 0 everywhere but
%...
%...       u(x,y,0) = 1 in a circle with center (-.5,-.5) and radius 0.4
%...
%...       u(x,y,0) = -1 in a circle with center (.5,.5) and radius 0.4
%...
%...   BCs :
%...
%...       u(x,y,t) = 0 on the boundary
%...
%... the following code computes a solution to Burgers equation
%...
    close all
    clear all
%...
%... start a stopwatch timer
    tic
%...
%... set global variables
    global eps nu 
    global nx ny nv x y D1x_up D1x_c3 D1x_c5 D1y_up D1y_c3 D1y_c5
%...
%... model parameters
    eps = 0.5;
    ne = 2;
%...
%... spatial grid
    x0 = -1.5; y0 = -1.5;
    xL = 1.5; yL = 1.5;
    nx = 101; ny = 101;
    dx = (xL - x0)/(nx-1); dy = (yL - y0)/(ny-1);
    x = [x0:dx:xL]; y = [y0:dy:yL];
%...
%... initial conditions
    u0 = zeros(nx*ny,1);
    nv = length(u0);
    for k = 1:nv
        xg = x0 + (k - nx*fix(k/nx)-1)*dx;
        yg = y0 + fix(k/ny)*dy;
    disk1 = (xg+.5)^2+(yg+.5)^2;
    if disk1 <= .16
        u0(k) = 1;
    else
        disk2 = (xg-.5)^2+(yg-.5)^2;
        if disk2 <= .16
            u0(k) = -1;
        end
    end
    end
%...    
    nu = zeros(nv,1);
%...
%... finite difference (FD) approximation of the spatial derivatives
%...
    D1x_up = two_point_upwind_D1(x,1);
    D1x_c3 = three_point_centered_D1(x);
    D1x_c5 = five_point_centered_D1(x);
%...
    D1y_up = two_point_upwind_D1(y,1);
    D1y_c3 = three_point_centered_D1(y);
    D1y_c5 = five_point_centered_D1(y);
%...  
%... call to ODE solver 
%...
    t = [0:.1:0.6];
    [tout,uout] = ode45(@generalized_burgers_pde,t,u0);
%...  
%... plot results 
%...
    [X Y] = meshgrid(x,y(ny:-1:1));
%...
    for j = 1:length(tout)
%...    
        figure
%...
        u(ny:-1:1,:) = reshape(uout(j,1:nv),nx,[])';
%...
        surf(X,Y,u,'FaceColor',[.95 .95 .95],'EdgeColor','none')
        hold
        axis([-1.5 1.5 -1.5 1.5 -1 1])    
        xlabel('x'); ylabel('y'); zlabel('u(x,y)');
        view([32 18]);
        camlight right;
        lighting gouraud;
    end
%...     
%... read the stopwatch timer
    toc