%... The MatMol Group (2016)
%...
%... Singular perturbation problem
%...
%... consider a two-tank chemical reactor system, where it is
%... required to maintain the concentration of liquid in the 
%... second tank at a certain level by the addition of reactant
%... through a control valve.
%...
%... This problem is a modified version of example 3.2 p 106-109
%... (Kokotovic, Khalil and O'Reilly, 1986).
%...
%... This system is controlled using state feedback. A linearized model of 
%... the complete system is given by
%...
%...
%... |   x(1:2)   |   | -0.2  +0.2  0    0 |   | x(1) |   | 0 |
%... |    t       |   |  0    -0.5  0.5  0 |   | x(2) |   | 0 |
%... |            | = |                    | * |      | + |   | u
%... | eps*x(3:4) |   |  0     0    0    1 |   | x(3) |   | 0 |
%... |      t     |   |  0     0   -1   -2 |   | x(4) |   | 1 |
%...
%...
%... where
%...
%...  x1          deviation in concentration of second tank (slow dynamics)
%...
%...  x2          deviation in concentration of first tank  (slow dynamics)
%...
%...  x3 and x4   state variables associated to the actuator (fast dynamics)
%...
%...  eps         scaling factor
%...
%...  u           state-feedback control in the form u(t) = - [k1 k2] x(t)
%...
%... the initial conditions (ICs) are taken as
%...
%... x1(0) = 2.5    x2(0) = 2.0    x3(0) = 0  x4(0) = 0
%...
%... Reference
%...
%... Kokotovic, Khalil and O'Reilly
%... Singular Perturbation Methods in Control: Analysis and Design 
%... Academic Press, 1986 (example 3.2, pp 106-109)
%...
%... the following code computes a solution to this problem
%...
     close all
     clear all
%...
%... start a stopwatch timer
     tic
%...
%... set global variables
     global A B eps K
%...
%... model parameters
     A = [-0.2  0.2  0.0  0.0;
           0.0 -0.5  0.5  0.0;
           0.0  0.0  0.0  1.0;
           0.0  0.0 -1.0 -2.0];
%...      
     B = [0 0 0 1]';
%...
     K = [7 1.5];     
%...
%... initial conditions
     t=[0:0.1:10];
     x = [2.5 2.0 0 0]';
%...  
%... call to ODE solver with eps = 0.1
%...
     eps = 0.1;
%...
     options = odeset('Mass',@mass,'MassSingular','no',...
                      'RelTol',1e-3,'AbsTol',1e-3);
%...
     [tout, xout] = ode15s(@two_tanks_odes,t,x,options);
%...
%...
     figure(1)
     subplot(2,1,1)
     plot(t,xout(:,1:2),'k');
     xlabel('t');
     ylabel('x1(t) and x2(t)');
     subplot(2,1,2)
     plot(t,xout(:,3:4),'k');
     xlabel('t');
     ylabel('x3(t) and x4(t)');
%...     
%... consider smaller eps = 0.05
%...
%... initial conditions
%     t=[0:0.1:10];
%     x = [2.5 2.0 0 0]';
%...
     eps = 0.05;
%...
     options = odeset('Mass',@mass,'MassSingular','no',...
                      'RelTol',1e-3,'AbsTol',1e-3);
%...
     [tout, xout] = ode15s(@two_tanks_odes,t,x,options);
%...
%...
     figure(1)
     subplot(2,1,1)
     hold on
     plot(t,xout(:,1:2),'k--');
     xlabel('t');
     ylabel('x_1(t) and x_2(t)');
     title('Singular perturbation problem');
     subplot(2,1,2)
     hold on
     plot(t,xout(:,3:4),'k--');
     xlabel('t');
     ylabel('x_3(t) and x_4(t)');
%...
%... turn to DAEs by setting eps = 0
%...
%... initial conditions
%     t=[0:0.1:10];
%     x = [2.5 2.0 0 0]';
%...
     eps = 0;
%...
     options = odeset('Mass',@mass,'MassSingular','yes',...
                      'RelTol',1e-3,'AbsTol',1e-3);
%...
     [tout, xout] = ode15s(@two_tanks_odes,t,x,options);
%...
%...
     figure(1)
     subplot(2,1,1)
     hold on
     plot(t,xout(:,1:2),'k:');
     xlabel('t');
     ylabel('x_1(t) and x_2(t)');
     title('Singular perturbation problem');
     subplot(2,1,2)
     hold on
     plot(t,xout(:,3:4),'k:');
     xlabel('t');
     ylabel('x_3(t) and x_4(t)');
%...
%... read the stopwatch timer
     tcpu=toc;

  
