nr = 100;
Name{nr} = 'Permeability';
figure(nr)
plot_mesh_1(rock.perm(:,1)/(milli*darcy),...
    G, 'name', Name{1},'o_daspect',[6 6 1], ...
    'l_cb','perm', 'o_cb', 1, 'figure', nr, 'showgrid', 2, ...
    'EA', 1, 'FA', 1, 'titl', '','x_lab', 'x', 'y_lab', 'y', ...
    'inter',   [], 'o_view', [35 35],'o_daspect', [3 3 1.5],  'o_cb', 2,...
    'o_ax',  2, 'dir', [])

nr = nr + 1;
Name{nr} = 'RelativePermeability';
% 1. Marker, 2. Color, 3. Markersize, 4. Linestyle, 5. LineWidth
% linestyles = {'none', '-',  '--', '-.', ':' };
% markerstyles = {'none', '.', 'o', 'd', '*' '+' 'x' 's'} ;
% colors = {'r',  [0 0.7 0], 'b', 'm', [0 0.7 0.7], [0.7 0 0.7], [0.5 0.5 0.7]};
% time = (DT:DT:t)/day;
optp = { [2 2 3 4 5 6 7], [1 2], 5, [1 2 3 4], [1.8] };
figure(nr)
Plot_val(kr,'x',x_kr,'savename','Relative_permeability','optp',optp,'x_lab',...
    'S','y_lab', 'Permeability','o_legend', [{'kr_1', 'kr_2'}], ...
    'revx', false, 'dir', [], 'figure', nr, 'titl', 'Relperm','o_ax', 3)
nr = nr + 1;

Name{nr} = 'Initial Pressure';
figure(nr)
plot_mesh(rSol.pressure/barsa, G, 'name', 'Pressurefield','o_daspect',[6 6 1], ...
    'o_ax', 0, 'l_cb', false, 'o_cb', 1, 'figure', nr, 'showgrid', 2, ...
    'EA', 1, 'FA', 1, 'titl', 'Pressure','x_lab', 'xdir', 'y_lab', 'ydir', ...
    'inter',   [], 'o_view', [0 90],'o_daspect', [3 3 3],  'o_cb', 2,...
    'l_cb', [],  'o_ax',  2, 'dir', [])
