%... The MatMol Group (2016)
     function xt=kdv3_adaptive_pde(t,x)
%...
%... Set global variables
     global tc
     global D1 D1z
     tc = t;
%...
%... Transfer dependent variables  
     u=x;
%...
%... Spatial derivatives and boundary conditions
%...   
     uz=D1*u;
     uzz=D1*uz;
	 uzzz=D1*uzz;
%...
%... Partial differential equations
%...
     ut=-6*u.*uz-uzzz;
%...
%... Transfer temporal derivatives
%...
     xt=ut;
