%... The MatMol Group (2016)
     function [x] = kdv3_exact(z,t)
%...
%... this function computes an exact solution to KdV3 equation
%...
     global s
%...     
     x = 0.5*s*(sech(0.5*sqrt(s)*(z-s*t))).^2;
