%... The MatMol Group (2016)
%...   Graetz problem
%...
%...   Tt = - Pe*v(r)*Tz + Tzz + (1/r)*Tr + Trr
%...
%...   0 < t < tmax   0 < r < 1   0 < z < L = 30 
%...
%...   Pe = Peclet number = 60 or 180
%...
%...   tmax = 0.5 when Pe = 60    tmax = 0.2 quand Pe = 180
%...
%...  v(r) = 2*(1-r^2) : parabolic velocity profile
%...
%...  I.C. :  T(z,r,0) = 0
%...
%...  BCs  :  Tr(z,0,t) = 0
%...
%...          T(z,1,t) = 1
%...
%...          T(0,r,t) = 0
%...
%...          Tz(L,r,t) = 0
%...
%...   In r = 0, l'Hospital rule gives:
%...
%...            1   dT         1   d2T
%...       lim --- ---- = lim --- -----
%...       r=0  r   dr    r=0  1   dr2
%...
%...  which leads to a special formulation of the PDE on the center line (r=0)
%...
%...   Tt = - Pe*v(r)*Tz + Tzz + 2*Trr
%...
%... the following code computes a solution to Graetz problem
%...
    close all
    clear all
%...
%... start a stopwatch timer
    tic
%...
%... set global variables
    global Pe v r_inv nv nz nr absc r dr D1z D1r D2z D2r
%...
%... spatial grid
    z0 = 0; zL = 30;
    nz = 101; dz = (zL-z0)/(nz-1); z = [z0:dz:zL];
%...
    r0 = 0; rR = 1;
    nr = 101; dr = (rR-r0)/(nr-1); r = [r0:dr:rR];
%...
%... model parameters
    Pe = 60;
    v = zeros(nz*nr,1);
    r_inv = zeros(nz*nr,1);
    for i = 1:nr
        if i == 1
            v((i-1)*nz+1:i*nz,1) = 2*(1-r(i)^2);
        else
            v((i-1)*nz+1:i*nz,1) = 2*(1-r(i)^2);
            r_inv((i-1)*nz+1:i*nz,1) = 1/r(i);
        end
    end
%...
%... initial conditions
    T0 = zeros(nz*nr,1);
    nv = length(T0);
%...
%... finite difference (FD) approximation of the spatial derivatives
%...
    D1z = four_point_biased_upwind_D1(z,1);
    D1r = five_point_centered_D1(r);
    D2z = five_point_centered_D2(z);
    D2r = five_point_centered_D2(r);
%...  
%... call to ODE solver 
%...
    t = [0:.05:.5];
%...
    [tout,Tout] = ode45(@Graetz_pde,t,T0);
%...  
%... impose BCs 
%...
    for k = 1:length(tout)
        Tout(k,1:nz) = Tout(k,nz+1:2*nz);        % BC along r = 0
        Tout(k,nv-nz+1:nv) = 1;                  % BC along r = R
        Tout(k,1:nz:nv-nz+1) = 0;                % BC along z = 0
        Tout(k,nz:nz:nv) = Tout(k,nz-1:nz:nv-1); % BC along z = L
    end
%...  
%... plot results 
%...
    [Z R] = meshgrid(z,r(nr:-1:1));
    [Z1 R1] = meshgrid(z,-r);
%...
    for j = 1:length(tout)
%...    
    figure
    u(nr:-1:1,:) = reshape(Tout(j,1:nv),nz,[])';
%...
    surf(Z,R,u,'EdgeColor','none')%[.95 .95 .95]
    hold
    surf(Z1,R1,u(nr:-1:1,:),'EdgeColor','none')%[.95 .95 .95]
    axis([z0 zL -rR rR 0 1]);
    xlabel('z'); ylabel('r'); zlabel('T(z,r)');
%     alpha(.8)
    view(-60,16)
    camlight right; 
    lighting gouraud; 
    pause
end
%...     
%... read the stopwatch timer
    toc
