%... The MatMol Group (2016)
%...
%... Batch Stirred Tank Reactor
%...
%... consider a BSTR in which the following reactions take place
%... (modified from Economou, Morari and Palsson, 1986)
%...
%... A <----> R
%...
%... the reaction rates are linear in either the component A or B,
%... and follow the Arrhenius temperature dependency
%...
%... kd = Cd*exp(-Ed/(R*T))
%...
%... kr = Cr*exp(-Er/(R*T))
%...
%... the material balances are given by
%...
%... A  = - kd*A + kr*B
%...  t  
%...
%... B  =   A0 + B0 - A
%...
%... the energy balance is given by
%...
%... T  = (kd*A - kr*B)*DH/(rho*cp)
%...  t   
%...
%... where
%...
%...  A       component concentration
%...
%...  B       component concentration
%...
%...  T       temperature
%...
%...  t       time
%...
%...  V       reactor volume
%...
%...  rho     density
%...
%...  cp      heat capacity
%...
%...  F       outlet flow rate
%...
%...  Cd      frequency constant (direct reaction)
%...
%...  Cr      frequency constant (reverse reaction)
%...
%...  Ed      activation energy (direct reaction)
%...
%...  Er      activation energy (reverse reaction)
%...
%...  R       gas constant
%...
%...
%... the initial conditions (ICs) are taken as
%...
%... A(t=0) = A0 = 1    B(t=0) = B0 = 0    T(t=0) = T0 = 430          
%...
%... Reference
%...
%... C.G. Economou, M. Morari and B.O. Palsson, 
%... Internal Model Control. 5. Extension to Nonlinear Systems, 
%... Ind. Eng. Chem. Process Des. Dev. 25 (1986), 403-411.
%...
%... the following code computes a solution to this problem
%...
     close all
     clear all
%...
%... start a stopwatch timer
     tic
%...
%... set global variables
     global A0 B0 rhocp Cd Cr Ed Er DH R
%...
%... model parameters
     rhocp = 1000;
     Cd = 5000;
     Cr = 1000000;
     Ed = 10000; 
     Er = 15000; 
     DH = 5000;
     R = 1.987;
%...
%... initial conditions
     A0 = 1;
     B0 = 0;
     T0 = 430;
     x = [A0 T0]';
%...
%... use 'homemade' Euler steps and interlaced solution of the algebraic
%... equation
     tf = 100;
     h = 0.5;
     t = [0:h:tf];
     nout = tf/h;
     tk = 0;
     yout=[A0 B0 T0];
     for iout=1:nout
       [xt] = bstr_odes_ae(tk,x);
       x = x + xt*h;
       tk = tk + h;
       yout = [yout ; x(1) A0+B0-x(1) x(2)];
     end
%...     
%... plot results
%...
     subplot(3,1,1)
     plot(t,yout(:,1),'k');
%     xlabel('t');
     ylabel('A(t)');
%     title('Component A concentration');
     subplot(3,1,2)
     plot(t,yout(:,2),'k');
%     xlabel('t');
     ylabel('B(t)');
%     title('Component B concentration')
     subplot(3,1,3)
     plot(t,yout(:,3),'k');
     xlabel('t');
     ylabel('T(t)');
%     title('Temperature');
%...
%... read the stopwatch timer
     tcpu=toc;

  
