%... The MatMol Group (2016)
%...
%... Culture of bacteria
%...
%... consider a batch reactor in which the following biological reaction takes place
%... (Bogaerts, 1999)
%...
%... nu S ----> X
%...
%... the specific reaction rates can be one of the following:
%...
%... constant:      mu = mumax
%...
%... Monod:         mu = mumax*S/(Km+S)
%...
%... Haldane:       mu = mumax*S/(Km+S+S^2)
%...
%... Contois:       mu = mumax*S/(Kc*X+S)
%...
%... the material balances are given by
%...
%... X  = phi = mu*X
%...  t  
%...
%... S  = -nu*phi = -nu*phi*X
%...  t  
%...
%... where
%...
%...  S             substrate concentration
%...
%...  X             biomass concentration
%...
%...  t             time
%...
%...  mu            specific growth rate
%...
%...  phi           reaction rate
%...
%...  mumax         maximum specific growth rate
%...
%...  Km, Ki, Kc    activation and inhibition constants
%...
%... the initial conditions (ICs) are taken as
%...
%... X(t=0) = 1.4 10^11    S(t=0) = 9
%...
%...
%... X(t=0) = 1.4 10^11    S(t=0) = 12
%...
%... Reference
%...
%... Ph. Bogaerts, 
%... Contribution � la mod�lisation math�matique pour la simulation et l'observation d'�tats des bioproc�d�s, 
%... Ph.D thesis, Universit� Libre de Bruxelles, 1999.
%...
%... the following code computes a solution to this problem
%...
     close all
     clear all
%...
%... start a stopwatch timer
     tic
%...
%... set global variables
     global nu mumax Km Ki Kc kinetics
%...
%... model parameters
     nu = 0.5e-11;
     mumax = 1.4;
     Km = 12;
     Ki = 3;
     Kc = 3e-11;
%...
%     kinetics = 'constant'         
%...
%     kinetics = 'monod'         
%...
%     kinetics = 'haldane'         
%...
     kinetics = 'contois'         
%...
%... initial, final time, plot interval
     t0 = 0;
     tf = 20;
     Dtplot = 0.1;
%...
%... initial conditions
      ICs = 'case_1'           
%...
%      ICs = 'case_2'           
%...
     switch ICs    
%...
%... case 1
       case('case_1')
           X = 1.4e11;
           S = 9;
%... case 2
       case('case_2')
           X = 1.4e11;
           S = 12;
%...
     end
     x = [X S]';
%...  
%... call to ODE solver (comment/decomment one of the methods to select a solver)
%...
%      method = 'ode45'     
%...
      method = 'ode15s'     
%...
     switch method    
%... ode45
       case('ode45')
           options = odeset('RelTol',1e-3,'AbsTol',1e-3);
           options = odeset(options,'Stats','on','Events',@events);
           t = [t0:Dtplot:tf];
           [tout, xout] = ode45(@bacteria_odes,t,x,options);
%... ode15s
       case('ode15s')
           options = odeset('RelTol',1e-3,'AbsTol',1e-3);
           options = odeset(options,'Stats','on','Events',@events);
           t = [t0:Dtplot:tf];
           [tout, xout] = ode15s(@bacteria_odes,t,x,options);
%...
     end
%...
%... plot results
     figure(1)
     plot(tout,xout(:,1),'k');
     xlabel('t');
     ylabel('X(t)');
%     title('Biomass concentration - constant law');
%     title('Biomass concentration - Monod law');
%     title('Biomass concentration - Haldane law');
     title('Biomass concentration - Contois law');
     figure(2)
     plot(tout,xout(:,2),'k');
     xlabel('t');
     ylabel('S(t)');
%     title('Substrate concentration - constant law')
%     title('Substrate concentration - Monod law')
%     title('Substrate concentration - Haldane law')
     title('Substrate concentration - Contois law')
%...
%... read the stopwatch timer
     tcpu=toc;

  
